---
name: Deploy Jenkins jobs
on:
  push:
    branches:
      - main
jobs:
  push:
    name: Deploy Jenkins jobs
    runs-on: ubuntu-latest
    if: github.repository == 'rakshithakamath94/nfs-ci-jobs'
    steps:
      - uses: actions/checkout@v2
      - name: build JJB container image
        run: docker build -t rakshithakamath94-nfs-ci-jobs -f tests/Containerfile .
      - name: update Jenkins Jobs
        run: docker run --rm --env="JENKINS_API_KEY=${{ secrets.JENKINS_API_KEY }}" --entrypoint=tests/deploy-nfs-ganesha-ci.sh rakshithakamath94-nfs-ci-jobs:latest
